### ISSUE TITLE
KeyError: 'POOLS'

### ISSUE THREAD

**Issue by red0bear** [anselal/antminer-monitor#139] opened 2018-10-30 12:13 UTC
Well i got error now ....

builtins.IndexError IndexError: list index out of range

**Comment by anselal** [comment] 2018-10-30 19:45
Need more info on that. Can you paste the complete error ?

**Comment by red0bear** [comment] 2018-10-30 19:46
How could do that ? Do you have a command line please ?

**Comment by red0bear** [comment] 2018-10-30 19:50
127.0.0.1 - - [30/Oct/2018 14:41:32] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "antminer-monitor/antminermonitor/blueprints/asicminer/views/antminer.py", line 105, in miners
    worker = active_pool[0]['User']

**Comment by red0bear** [comment] 2018-10-30 19:53
builtins.KeyError

KeyError: 'POOLS'
Traceback (most recent call last)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise

    raise value

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise

    raise value

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view

    return func(*args, **kwargs)

    File "antminer-monitor/antminermonitor/blueprints/asicminer/views/antminer.py", line 102, in miners

    pool for pool in miner_pools['POOLS'] #if pool['Stratum Active']

    KeyError: 'POOL

**Comment by anselal** [comment] 2018-10-30 19:56
Will look into that. I will need to add some exceptions and print some info about the miner like the IP Address so we have an ideawhich machine is causing tbe error

**Comment by anselal** [comment] 2018-11-02 13:11
This was closed with #124 
Maybe you are running an older  version ?

**Comment by red0bear** [comment] 2018-11-02 13:19
im running the last version i get in git hub. Did you make some update right now ?

**Comment by anselal** [comment] 2018-11-04 16:38
Please try to increase the socket timeout in the lib/pycgminer.py file and let me know if that helped

**Comment by red0bear** [comment] 2018-11-04 16:40
Ok.

**Comment by anselal** [comment] 2018-11-05 11:42
Any feedback ?

**Comment by red0bear** [comment] 2018-11-05 12:03
@anselal im so sorry ... i didnt get enough time time to see that. i will do soon. Im bit busy.

**Comment by red0bear** [comment] 2018-11-05 12:11
sock.settimeout(1) ????

**Comment by anselal** [comment] 2018-11-05 12:28
OK. Let it run for a couple of days and it fixes the error come back and close the issue

**Comment by fcabrera1109** [comment] 2018-11-08 19:33
HI guys I have same issue it started once I added the last miner somewhere around 50 I did increase the socket as directed above and no change

**Comment by red0bear** [comment] 2018-11-08 19:35
@fcabrera1109 what version from python are you using ? i faced anothers errors but seem ok right now for me .

**Comment by fcabrera1109** [comment] 2018-11-08 19:41
Python 2.7.5

**Comment by red0bear** [comment] 2018-11-08 19:43
@fcabrera1109  can you try python 3.6  ? im doing this on it.

**Comment by fcabrera1109** [comment] 2018-11-08 19:43
let me try and install

**Comment by fcabrera1109** [comment] 2018-11-08 19:51
python3.6 manage.py run -h 0.0.0.0 -p 5000 ran this got 

File "manage.py", line 3, in <module>
    from flask.cli import FlaskGroup
ModuleNotFoundError: No module named 'flask'

**Comment by red0bear** [comment] 2018-11-08 19:52
Did you install are requirements ?

**Comment by fcabrera1109** [comment] 2018-11-08 19:56
I believe so when I run "pip install flask". says all requirements already installed

**Comment by fcabrera1109** [comment] 2018-11-08 19:58
yes all installed and got this when I try and load page


Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/antminer-monitor-master/antminermonitor/blueprints/asicminer/views/antminer.py", line 105, in miners
    worker = active_pool[0]['User']
IndexError: list index out of range

**Comment by red0bear** [comment] 2018-11-08 19:58
hummmm .... i think some missing lib like me .... when i try install first time ... now you need do a work around to discover whats going on in package.

**Comment by fcabrera1109** [comment] 2018-11-08 19:59
Do you've many miners? It ws working fine until the last one I added and broke page

**Comment by red0bear** [comment] 2018-11-08 20:06
in antminer.py make a change 

pool for pool in miner_pools['POOLS']  if pool['Stratum Active']

to
@pool for pool in miner_pools['POOLS'] #if pool['Stratum Active']

and try again .

**Comment by fcabrera1109** [comment] 2018-11-08 20:12
FYI I started with new DB and working again. I believe it a limitation of DB or code display when to many rows

**Comment by anselal** [comment] 2018-11-08 20:12
@red0bear commenting out the if statement will make the software always showing the 1st worker regardless if the miner has switched to the 2nd or 3rd pool

**Comment by fcabrera1109** [comment] 2018-11-08 20:12
I will start adding again and see when it breaks

**Comment by anselal** [comment] 2018-11-08 20:13
My software has no limits !!!! The limit is the sky !!!!

**Comment by red0bear** [comment] 2018-11-08 20:15
@anselal limits is only money in your pocket to buy a good computer.

**Comment by anselal** [comment] 2018-11-08 20:18
Money is irelevant

**Comment by fcabrera1109** [comment] 2018-11-08 20:30
@anselal any idea why its breaking at around 40 miners.  I think its not the actual active miner pane breaking it but the inactive/error one.

**Comment by fcabrera1109** [comment] 2018-11-08 20:31
if that she case its 13-14 errors.

**Comment by fcabrera1109** [comment] 2018-11-08 20:38
that worked!!

fixed it :)

**Comment by red0bear** [comment] 2018-11-08 20:40
@fcabrera1109 what ? :-)

**Comment by anselal** [comment] 2018-11-08 22:05
My software can handle hundreds maybe even thousands of miners.

**Comment by anselal** [comment] 2018-11-08 22:06
@fcabrera1109 feedback please

**Comment by fcabrera1109** [comment] 2018-11-09 02:14
the change anselal had me make worked.  

in antminer.py make a change

pool for pool in miner_pools['POOLS'] if pool['Stratum Active']

to
@pool for pool in miner_pools['POOLS'] #if pool['Stratum Active']

and try again .

**Comment by anselal** [comment] 2018-11-09 06:16
I explained abive why the code is wrong. It will show the wrong pool user if tje miner switches to other than the first.

I will taoe a look at it.

@fcabrera1109 what models are your miners ?

**Comment by anselal** [comment] 2018-11-09 19:57
This is why you need the if statement you deleted.

**Comment by fcabrera1109** [comment] 2018-11-09 20:47
If I remove the # and unremarkable it it still gives same error,

**Comment by red0bear** [comment] 2018-11-09 23:50
@fcabrera1109  @anselal  well ... here i just make that and  i still get errors. But at least it recover from error. I see more a problem with exceptions.

**Comment by red0bear** [comment] 2018-11-10 01:31
@anselal this what you want is dangerous. i think we need another way to provide you what you need .

**Comment by anselal** [comment] 2018-11-10 01:33
I have done this many times. Sorry if you dont trust me but there is no other way.

**Comment by red0bear** [comment] 2018-11-10 01:34
Hehehe .... lets stay with error for while.

**Comment by anselal** [comment] 2018-11-10 01:35
As you wish

**Comment by fcabrera1109** [comment] 2018-11-10 02:02
anselal I think the biggest issue is not the fact that there are bugs but the fact that the entire things breaks when something it does not like,.  I can't even go back and remove a miner that cause the issue I have to start from scratch.   Any idea why you didn't use mysql backend so I could login and delete a trebled miner from the db?

**Comment by anselal** [comment] 2018-11-10 06:57
As you say, if you want to delete a miner to fix the error tjan the problem is the miner and not the software.
Besides that you can edit the sqlite3 database too. In fact it is more easily as mysql.

And to answer your question, i used sqlite3 because it doesn't need any setup from the users side. You can point the database to a mysql if you want and it will work. It will also create the tables 4 you.

**Comment by devilz696** [comment] 2019-01-14 07:13
Hi!  got same error at ~180 miner. Any working solutions?
Python 3.6.6

`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/var/antminer-monitor/antminermonitor/blueprints/asicminer/views/antminer.py", line 113, in miners
    for chain in miner_stats['STATS'][1].keys()
IndexError: list index out of range`

**Comment by anselal** [comment] 2019-01-14 09:06
@devilz696 According to your output it crashes while trying to filter the ASIC chips.

It could be due to socket timeout, error on miner API.
You could try to increase the socket timeout to a value like 5 or 10 like I describe above at https://github.com/anselal/antminer-monitor/issues/139#issuecomment-435684717

Please let me know if that helped.

@red0bear Any feedback ???

**Comment by devilz696** [comment] 2019-01-14 09:46
@anselal tryed timeout = 10, nothing has changed :(

**Comment by anselal** [comment] 2019-01-14 09:52
@devilz696 did the error appear after you added a miner ?

Perhaps the miner's API has some issues

**Comment by anselal** [comment] 2019-01-14 09:54
If yes, there is a way to check if the API has indeed some issues.
Also, there is a way to remove the miner from the database if you know your way with python. If not I can assist you by connecting to your machine and remote the miner from the database

**Comment by red0bear** [comment] 2019-01-14 10:54
@anselal @devilz696 ... here still give error but after did change in code i can recover the error.

**Comment by red0bear** [comment] 2019-01-14 12:50
@anselal 

the change anselal had me make worked.

in antminer.py make a change

pool for pool in miner_pools['POOLS'] if pool['Stratum Active']

to
@pool for pool in miner_pools['POOLS'] #if pool['Stratum Active']

and try again .

This solution still given error ... but you can recover and back to see machines .....

**Comment by anselal** [comment] 2019-01-14 13:58
@devilz696 can you try this ?

**Closed** 2019-12-18 20:53 UTC
